# Generated by Django 5.0.6 on 2024-06-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='O', max_length=10)),
                ('photo', models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='images/')),
                ('personal_number', models.CharField(default='', max_length=12, unique=True)),
                ('personal_birthdate', models.DateField(blank=True, null=True)),
                ('city', models.CharField(choices=[('Other', 'Other'), ('Gori', 'Gori'), ('Tbilisi', 'Tbilisi'), ('Batumi', 'Batumi'), ('Zugdidi', 'Zugdidi'), ('Telavi', 'Telavi'), ('Poti', 'Poti'), ('Kobuleti', 'Kobuleti')], default='Other', max_length=30)),
            ],
        ),
    ]
