# Generated by Django 5.0.6 on 2024-06-29 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('Other', 'Other'), ('Relative', 'Relative'), ('Colleague', 'Colleague')], max_length=10)),
                ('connected_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_to', to='api.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api.person')),
            ],
        ),
    ]
