# Generated by Django 5.0.6 on 2024-05-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='personal_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='personal_number',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='personal_photo',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
