# Generated by Django 5.0.6 on 2024-05-31 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_city_person_gender_person_personal_birthdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='personal_photo',
            new_name='photo',
        ),
    ]
