# Generated by Django 5.0.6 on 2024-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_personal_photo_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='connection',
            field=models.CharField(choices=[('O', 'Other'), ('R', 'Relative')], default='O', max_length=1),
        ),
    ]
