# Generated by Django 5.0.6 on 2024-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='connection',
            field=models.CharField(choices=[('Other', 'Other'), ('Relative', 'Relative')], default='O', max_length=10),
        ),
    ]
