# Generated by Django 5.0.6 on 2024-06-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_person_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='connection',
            field=models.CharField(choices=[('Other', 'Other'), ('Persons', 'Persons')], default='Other', max_length=10),
        ),
    ]
