# Generated by Django 5.0.6 on 2024-06-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_person_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='persons',
            field=models.CharField(choices=[('Other', 'Other'), ('Persons', 'Persons')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='connection',
            field=models.CharField(choices=[('Other', 'Other'), ('Relative', 'Relative'), ('Colleague', 'Colleague'), ('Familiar', 'Familiar')], default='Other', max_length=10),
        ),
    ]
