# Generated by Django 5.0.6 on 2024-06-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_person_persons_alter_person_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='persons',
            field=models.CharField(choices=[('None', 'None'), ('Persons', 'Persons')], default='None', max_length=10),
        ),
    ]
