# Generated by Django 5.0.6 on 2024-06-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_person_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='persons',
            field=models.ForeignKey(default='Persons', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
