# Generated by Django 5.0.6 on 2024-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_person_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='persons',
            field=models.CharField(choices=[('None', 'None'), ('Persons', 'Persons')], default='Persons', max_length=10),
        ),
    ]
